package dev.rgcb.scholar.document;
public enum SemanticStyle { BODY_TEXT, TITLE, SUBTITLE, AUTHOR, AFFILIATION, ABSTRACT, KEYWORDS, FIGURE_CAPTION, TABLE_CAPTION, EQUATION, REFERENCE, FOOTNOTE, CODE }
