package dev.rgcb.scholar.editor;

/** Platform-neutral icon identity resolved by the Minecraft client. */
public enum EditorActionIcon {
    NEW_DOCUMENT,
    OPEN,
    SAVE,
    HOME,
    UNDO,
    REDO,
    CUT,
    COPY,
    PASTE,
    DELETE,
    BOLD,
    ITALIC,
    UNDERLINE,
    SUPERSCRIPT,
    SUBSCRIPT,
    ALIGN_LEFT,
    ALIGN_CENTER,
    ALIGN_RIGHT,
    ALIGN_JUSTIFY,
    LINE_SPACING,
    INDENT_DECREASE,
    INDENT_INCREASE,
    STYLE,
    EQUATION,
    TABLE,
    DATASET,
    UNIT,
    PLOT,
    FIGURE,
    REFERENCE,
    TOC,
    DIAGRAM,
    ELECTRICAL,
    MECHANICAL,
    VIEW,
    OUTLINE,
    ZOOM_OUT,
    ZOOM_IN,
    FIT_PAGE,
    FIT_WIDTH
}
